import { Category, Product } from './types';

export const MOCK_PRODUCTS: Product[] = [
  {
    id: '1',
    name: 'Royal Habesha Kemis',
    price: 250,
    currency: '€',
    category: Category.FASHION,
    description: 'Traditional hand-woven cotton dress with intricate Tibeb embroidery.',
    detailedHistory: 'The Habesha Kemis is the traditional attire of Ethiopian women. Made from shemma (hand-woven cotton), the tibeb (embroidery) on the edges represents specific regions and status. This specific design features the Queen of Sheba motif.',
    imageUrl: 'https://picsum.photos/id/400/800/800', // Placeholder
    inStock: true,
  },
  {
    id: '2',
    name: 'Orthodox Coptic Cross (Silver)',
    price: 120,
    currency: '€',
    category: Category.ACCESSORIES,
    description: 'Handcrafted silver pendant featuring Lalibela cross designs.',
    detailedHistory: 'Ethiopian crosses are unique in their intricate lattice style, often representing the order of the universe. This piece is inspired by the rock-hewn churches of Lalibela, crafted by artisans in Aksum using the lost-wax casting method.',
    imageUrl: 'https://picsum.photos/id/300/800/800',
    inStock: true,
  },
  {
    id: '3',
    name: 'Jebena Coffee Set',
    price: 85,
    currency: '€',
    category: Category.HOME,
    description: 'Complete traditional clay coffee pot (Jebena) with cups (Sini).',
    detailedHistory: 'The coffee ceremony is the backbone of Ethiopian social life. The Jebena is a spherical clay pot used to brew coffee over charcoal. This set includes the Jebena, a rekebot (tray), and 6 sini (cups), sourced from potteries in Jimma, the birthplace of coffee.',
    imageUrl: 'https://picsum.photos/id/450/800/800',
    inStock: true,
  },
  {
    id: '4',
    name: 'St. George Slaying the Dragon',
    price: 450,
    currency: '€',
    category: Category.ART,
    description: 'Traditional painting on goatskin vellum.',
    detailedHistory: 'Ethiopian iconography has a distinct style dating back to the 4th century. This piece depicts St. George, a patron saint of Ethiopia, painted using natural pigments on prepared goatskin, following the ancient techniques of church monasteries.',
    imageUrl: 'https://picsum.photos/id/500/800/800',
    inStock: true,
  },
  {
    id: '5',
    name: 'Modern Tibeb Hoodie',
    price: 65,
    currency: '€',
    category: Category.FASHION,
    description: 'Contemporary streetwear featuring traditional weaving patterns.',
    detailedHistory: 'Bridging the gap between Addis Ababa street style and ancient tradition. This hoodie incorporates genuine hand-woven tibeb strips sewn onto high-quality organic cotton fleece, perfect for the European winter.',
    imageUrl: 'https://picsum.photos/id/600/800/800',
    inStock: true,
  },
  {
    id: '6',
    name: 'Woven Harar Basket (Mesob)',
    price: 110,
    currency: '€',
    category: Category.HOME,
    description: 'Large colorful woven basket used for serving communal meals.',
    detailedHistory: 'The Mesob is not just a table; it is a symbol of unity. People gather around it to eat Injera from a shared plate. These baskets are woven by women in the Harar region using dried grass and natural dyes.',
    imageUrl: 'https://picsum.photos/id/700/800/800',
    inStock: false,
  },
];